// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasezhuEchart: typeof import('./src/components/page-echarts/src/basezhu-echart.vue')['default']
    MapEchart: typeof import('./src/components/page-echarts/src/map-echart.vue')['default']
    PieEchart: typeof import('./src/components/page-echarts/src/pie-echart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeEchart: typeof import('./src/components/page-echarts/src/time-echart.vue')['default']
    ZhuEchart: typeof import('./src/components/page-echarts/src/zhu-echart.vue')['default']
  }
}

export {}
